### ISSUE TITLE
GeoIPAutoUpdater fails updating geoip2 database with .mmdb file ending

### ISSUE THREAD

**Issue by s1awa** [matomo-org/matomo#11049]
**Error: Encountered unsupported archive type 'mmdb.gz'**

MaxMind geoip2 uses new format for goip database with .mmdb file ending.
e.g. GeoLite2-City.mmdb
http://dev.maxmind.com/geoip/geoip2/geolite2/

The download url for the file is:
http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz

cron/archive.php generates an error when auto updating.

```
INFO CoreAdminHome[2016-12-20 01:13:21] [d3190] Scheduler: executing task Piwik\Plugins\UserCountry\GeoIPAutoUpdater.update...
ERROR UserCountry[2016-12-20 01:13:21] [d3190] /var/www/example.com/plugins/UserCountry/GeoIPAutoUpdater.php(489): Encountered unsupported archive type 'mmdb.gz'.
  #0 /var/www/example.com/plugins/UserCountry/GeoIPAutoUpdater.php(471): Piwik\Plugins\UserCountry\GeoIPAutoUpdater::checkForSupportedArchiveType('mmdb.gz')
  #1 /var/www/example.com/plugins/UserCountry/GeoIPAutoUpdater.php(134): Piwik\Plugins\UserCountry\GeoIPAutoUpdater::getGeoIPUrlExtension('http://geolite....')
  #2 /var/www/example.com/plugins/UserCountry/GeoIPAutoUpdater.php(96): Piwik\Plugins\UserCountry\GeoIPAutoUpdater->downloadFile('loc', 'http://geolite....')
  #3 [internal function]: Piwik\Plugins\UserCountry\GeoIPAutoUpdater->update(NULL)
  #4 /var/www/example.com/core/Scheduler/Scheduler.php(227): call_user_func(Array, NULL)
  #5 /var/www/example.com/core/Scheduler/Scheduler.php(124): Piwik\Scheduler\Scheduler->executeTask(Object(Piwik\Plugins\UserCountry\GeoIPAutoUpdater))
  #6 /var/www/example.com/plugins/CoreAdminHome/API.php(58): Piwik\Scheduler\Scheduler->run()
  #7 /var/www/example.com/core/CronArchive.php(536): Piwik\Plugins\CoreAdminHome\API->runScheduledTasks()
  #8 /var/www/example.com/core/CronArchive.php(290): Piwik\CronArchive->runScheduledTasks()
  #9 /var/www/example.com/core/Access.php(469): Piwik\CronArchive->Piwik\{closure}()
  #10 /var/www/example.com/core/CronArchive.php(292): Piwik\Access::doAsSuperUser(Object(Closure))
  #11 /var/www/example.com/plugins/CoreAdminHome/API.php(179): Piwik\CronArchive->main()
  #12 [internal function]: Piwik\Plugins\CoreAdminHome\API->runCronArchiving()
  #13 /var/www/example.com/core/API/Proxy.php(219): call_user_func_array(Array, Array)
  #14 /var/www/example.com/core/API/Request.php(236): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'runCronArchivin...', Array)
  #15 /var/www/example.com/plugins/API/Controller.php(40): Piwik\API\Request->process()
  #16 [internal function]: Piwik\Plugins\API\Controller->index()
  #17 /var/www/example.com/core/FrontController.php(518): call_user_func_array(Array, Array)
  #18 /var/www/example.com/core/FrontController.php(122): Piwik\FrontController->doDispatch('API', false, Array)
  #19 /var/www/example.com/core/dispatch.php(34): Piwik\FrontController->dispatch()
  #20 /var/www/example.com/index.php(27): require_once('/var/www/exampl...')
  #21 /var/www/example.com/misc/cron/archive.php(70): require_once('/var/www/exampl...')
  #22 {main}
INFO CoreAdminHome[2016-12-20 01:13:21] [d3190] Scheduler: finished. Time elapsed: 0.013s
```

**Comment by mattab** [comment]
@s1awa  thanks for the report. i've just added the extension to our white list in: https://github.com/piwik/piwik/pull/11081/files

Could you check if it works after updating the PR, since I haven't tested?

**Comment by s1awa** [comment]
@mattab 

 **The downloaded file is not a valid GeoIP database. Please re-check the URL or download the file manually.**

There are more checks somewhere for downloaded GeoIP Databases.

```
INFO UserCountry[2016-12-26 01:22:59] [5fd6a] GeoIPAutoUpdater: successfully downloaded 'http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz'
INFO UserCountry[2016-12-26 01:23:00] [5fd6a] GeoIPAutoUpdater: Encountered PHP error when testing newly downloaded GeoIP database: 8: Undefined offset: -16776960 on line 1705 of /home/iizi/analytics/libs/MaxMindGeoIP/geoip.inc.
ERROR UserCountry[2016-12-26 01:23:00] [5fd6a] /home/iizi/analytics/plugins/UserCountry/GeoIPAutoUpdater.php(161): GeoIPAutoUpdater: failed to unzip '/home/iizi/analytics/misc/GeoIPCity.dat.mmdb.gz' after downloading 'http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz': The downloaded file is not a valid GeoIP database. Please re-check the URL or download the file manually.
  #0 /home/iizi/analytics/plugins/UserCountry/GeoIPAutoUpdater.php(96): Piwik\Plugins\UserCountry\GeoIPAutoUpdater->downloadFile('loc', 'http://geolite....')
  #1 [internal function]: Piwik\Plugins\UserCountry\GeoIPAutoUpdater->update(NULL)
  #2 /home/iizi/analytics/core/Scheduler/Scheduler.php(227): call_user_func(Array, NULL)
  #3 /home/iizi/analytics/core/Scheduler/Scheduler.php(124): Piwik\Scheduler\Scheduler->executeTask(Object(Piwik\Plugins\UserCountry\GeoIPAutoUpdater))
  #4 /home/iizi/analytics/plugins/CoreAdminHome/API.php(58): Piwik\Scheduler\Scheduler->run()
  #5 /home/iizi/analytics/core/CronArchive.php(536): Piwik\Plugins\CoreAdminHome\API->runScheduledTasks()
  #6 /home/iizi/analytics/core/CronArchive.php(290): Piwik\CronArchive->runScheduledTasks()
  #7 /home/iizi/analytics/core/Access.php(469): Piwik\CronArchive->Piwik\{closure}()
  #8 /home/iizi/analytics/core/CronArchive.php(292): Piwik\Access::doAsSuperUser(Object(Closure))
  #9 /home/iizi/analytics/plugins/CoreAdminHome/API.php(179): Piwik\CronArchive->main()
  #10 [internal function]: Piwik\Plugins\CoreAdminHome\API->runCronArchiving()
  #11 /home/iizi/analytics/core/API/Proxy.php(219): call_user_func_array(Array, Array)
  #12 /home/iizi/analytics/core/API/Request.php(236): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'runCronArchivin...', Array)
  #13 /home/iizi/analytics/plugins/API/Controller.php(40): Piwik\API\Request->process()
  #14 [internal function]: Piwik\Plugins\API\Controller->index()
  #15 /home/iizi/analytics/core/FrontController.php(518): call_user_func_array(Array, Array)
  #16 /home/iizi/analytics/core/FrontController.php(122): Piwik\FrontController->doDispatch('API', false, Array)
  #17 /home/iizi/analytics/core/dispatch.php(34): Piwik\FrontController->dispatch()
  #18 /home/iizi/analytics/index.php(27): require_once('/home/iizi/anal...')
  #19 /home/iizi/analytics/misc/cron/archive.php(70): require_once('/home/iizi/anal...')
  #20 {main}
INFO CoreAdminHome[2016-12-26 01:23:00] [5fd6a] Scheduler: finished. Time elapsed: 0.803s
```

**Comment by s1awa** [comment]
@mattab 
GeoIP2 Plugin is buggy atm.
So the fix might work when the plugin is fixed.

https://github.com/piwik/piwik/issues/11157

**Comment by sgiehl** [comment]
Matomo 3.5.0 now includes a GeoIp2 plugin. This fully support the new mmdb format.
