### ISSUE TITLE
GDPR tool doesn't work when selecting all websites

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#12842]
This could be related to https://github.com/matomo-org/matomo/issues/12312

The API-URL the tool tries to access is 
`
index.php?date=1998-01-01,today&doNotFetchActions=1&filter_limit=401&format=JSON2&idSite=all&method=Live.getLastVisitsDetails&module=API&period=range&segment=countryCode%3D%3DDE
`

```
"An unexpected website was found in the request: website id was set to '1' 
.#0 /home/lukas/public_html/matomocopy/plugins/SitesManager/API.php(222): Piwik\\Site::setSiteFromArray(1, false)
#1 /home/lukas/public_html/matomocopy/core/Site.php(73): Piwik\\Plugins\\SitesManager\\API-&gt;getSiteFromId(1)
#2 /home/lukas/public_html/matomocopy/plugins/Live/Model.php(298): Piwik\\Site-&gt;__construct(Array)
#3 /home/lukas/public_html/matomocopy/plugins/Live/Model.php(335): Piwik\\Plugins\\Live\\Model-&gt;makeSite(Array)
#4 /home/lukas/public_html/matomocopy/plugins/Live/Model.php(244): Piwik\\Plugins\\Live\\Model-&gt;getWhereClauseAndBind('log_visit.idsit...', Array, Array, 'range', '1998-01-01,toda...', false, false)
#5 /home/lukas/public_html/matomocopy/plugins/Live/Model.php(39): Piwik\\Plugins\\Live\\Model-&gt;makeLogVisitsQueryString(Array, 'range', '1998-01-01,toda...', 'countryCode%3D%...', 0, 401, false, false, '')
#6 /home/lukas/public_html/matomocopy/plugins/Live/API.php(396): Piwik\\Plugins\\Live\\Model-&gt;queryLogVisits(Array, 'range', '1998-01-01,toda...', 'countryCode%3D%...', 0, 401, false, false, '')
#7 /home/lukas/public_html/matomocopy/plugins/Live/API.php(181): Piwik\\Plugins\\Live\\API-&gt;loadLastVisitorDetailsFromDatabase(Array, 'range', '1998-01-01,toda...', 'countryCode%3D%...', 0, 401, false, '', false)
#8 [internal function]: Piwik\\Plugins\\Live\\API-&gt;getLastVisitsDetails(Array, 'range', '1998-01-01,toda...', 'countryCode%3D%...', false, false, false, '1')
#9 /home/lukas/public_html/matomocopy/core/API/Proxy.php(236): call_user_func_array(Array, Array)
#10 /home/lukas/public_html/matomocopy/core/API/Request.php(253): Piwik\\API\\Proxy-&gt;call('\\\\Piwik\\\\Plugins\\\\...', 'getLastVisitsDe...', Array)
#11 /home/lukas/public_html/matomocopy/plugins/API/Controller.php(41): Piwik\\API\\Request-&gt;process()
#12 [internal function]: Piwik\\Plugins\\API\\Controller-&gt;index()
#13 /home/lukas/public_html/matomocopy/core/FrontController.php(559): call_user_func_array(Array, Array)
#14 /home/lukas/public_html/matomocopy/core/FrontController.php(137): Piwik\\FrontController-&gt;doDispatch('API', false, Array)
#15 /home/lukas/public_html/matomocopy/core/dispatch.php(34): Piwik\\FrontController-&gt;dispatch()
#16 /home/lukas/public_html/matomocopy/index.php(27): require_once('/home/lukas/pub...')
#17 {main}"
```
Quick debugging show that `$infoSite` is empty here:
https://github.com/matomo-org/matomo/blob/7cf4525d2c241b382964ceb8ab7ffa7deeb6b991/core/Site.php#L142

**Comment by tsteur** [comment]
As mentioned in check I recommend you check if `$_POST['token_auth']` is set. Depending on the size of the request etc this might not be set.

**Comment by Findus23** [comment]
I don't think it is the POST size as the POST data only consists of the token_auth (I am talking about the first request fetching the list, not the request actually exporting/deleting the data)

![grafik](https://user-images.githubusercontent.com/6266037/39689423-05c6d316-51d7-11e8-92fd-63ca581f6faf.png)

This can even be reproduced by making a GET to `http://localhost/matomocopy/index.php?module=API&method=Live.getLastVisitsDetails&idSite=all&period=month&date=today&format=JSON&token_auth=dfa[...]de` without the GDPR tool which makes me think it is the same issue as https://github.com/matomo-org/matomo/issues/12312
