### ISSUE TITLE
Row evolution broken

### ISSUE THREAD

**Issue by chris246** [matomo-org/matomo#12862]
Opening row evolutions (on Dashboard > Pages) throws the following error:
`Error: Expected date to be an instance of \Piwik\Date`

Matomo Version 3.5.0

**Comment by sgiehl** [comment]
Could you post the full querystring of the page that caused the error? Would maybe help to reproduce and fix.

**Comment by mattab** [comment]
Thanks for the report @chris246, it is reproducible in Dashboard > Pages widget, getting:

```
Expected date to be an instance of \Piwik\Date

Go Back | Go to Matomo
Stack trace

#0 www/plugins/CoreHome/Controller.php(249): Piwik\Plugins\CoreHome\DataTableRowAction\RowEvolution->__construct(1, NULL, NULL)
#1 www/plugins/CoreHome/Controller.php(215): Piwik\Plugins\CoreHome\Controller->makeRowEvolution(false)
#2 [internal function]: Piwik\Plugins\CoreHome\Controller->getRowEvolutionPopover()
#3 www/core/FrontController.php(559): call_user_func_array(Array, Array)
#4 www/core/FrontController.php(137): Piwik\FrontController->doDispatch('CoreHome', 'getRowEvolution...', Array)
#5 www/core/dispatch.php(34): Piwik\FrontController->dispatch()
#6 www/index.php(27): require_once('/
#7 {main}
```
