### ISSUE TITLE
When there is a memory error in core:archive process, have a way to see the backtrace

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13196]
## Use case
* A core:archive process fails with exhausted memory errors. 
* We need to know what code path was active when the archiving failed.

### Example failure from cron:

```
Error: {"type":1,"message":"Allowed memory size of 8589934592 bytes exhausted (tried to allocate 20480 bytes)","file":"\/core\/DataTable\/Row.php","line":91}
``` 

### Example failure with the `define('PIWIK_PRINT_ERROR_BACKTRACE', true);` in bootstrap.php

```
INFO [2018-07-23 15:51:47] 143396  SUMMARY OF ERRORS
INFO [2018-07-23 15:51:47] 143396  Error: Got invalid response from API request: ?module=API&method=API.get&idSite=8&period=year&date=last5&format=php&trigger=archivephp. Response was 'PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 20480 bytes) in /core/DataTable/Row.php on line 91 a:2:{s:6:"result";s:5:"error";s:7:"message";s:832:"The request requested too much data. To avoid this error, please try to reduce the filter limit. #0 [internal function]: Piwik\Plugins\Cloud\Controller-&gt;safemode(Array)
 #1 /core/FrontController.php(559): call_user_func_array(Array, Array)
 #2 /core/FrontController.php(137): Piwik\FrontController-&gt;doDispatch('Cloud', 'safemode', Array) 
#3 /core/FrontController.php(88): Piwik\FrontController-&gt;dispatch('CorePluginsAdmi...', 'safemode', Array) 
#4 /core/FrontController.php(229): Piwik\FrontController::generateSafeModeOutputFromError(Array) 
#5 [internal function]: Piwik\FrontController::triggerSafeModeWhenError() 
#6 {main}";}'
ERROR [2018-07-23 15:51:47] 143396  1 total errors during this script execution, please investigate and try and fix these errors.

```

## Expected instead

when we set  `define('PIWIK_PRINT_ERROR_BACKTRACE', true);` in bootstrap.php then we would expect somehow to see the original backtrace of the code path that failed, rather than the backtrace of the safe mode.

**Comment by diosmosis** [comment]
@mattab fatal errors don't leave a stack trace so this isn't do-able. Static variables, however, remain so we can build pieces of the stack traces by marking when certain methods start/complete. Will be doing that.
