### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14182]
I have been seeing this error in sentry and nobody seems to have reported it before
It happens every Monday when the weekly email report is sent and doesn't seem to break anything obvious.

```
ErrorException: Invalid argument supplied for foreach()
#23 matomo/plugins/ScheduledReports/API.php(712): handleError
#22 matomo/plugins/ScheduledReports/API.php(712): validateReportParameters
#21 matomo/plugins/ScheduledReports/API.php(348): generateReport
#20 matomo/plugins/ScheduledReports/API.php(599): Piwik\Plugins\ScheduledReports\{closure}
#19 matomo/core/Context.php(75): changeIdSite
#18 matomo/plugins/ScheduledReports/API.php(668): sendReport
#17 matomo/plugins/ScheduledReports/API.php(0): call_user_func
#16 matomo/core/Scheduler/Scheduler.php(246): executeTask
#15 matomo/core/Scheduler/Scheduler.php(136): run
#14 matomo/plugins/CoreAdminHome/API.php(66): runScheduledTasks
#13 matomo/core/CronArchive.php(612): runScheduledTasks
#12 matomo/core/CronArchive.php(317): Piwik\{closure}
#11 matomo/core/Access.php(628): doAsSuperUser
#10 matomo/core/CronArchive.php(319): main
#9 matomo/plugins/CoreConsole/Commands/CoreArchiver.php(27): execute
#8 matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): run
#7 matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): doRunCommand
#6 matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): doRun
#5 matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(0): call_user_func
#4 matomo/core/Console.php(98): Piwik\{closure}
#3 matomo/core/Access.php(628): doAsSuperUser
#2 matomo/core/Console.php(99): doRun
#1 matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): run
#0 matomo/console(27): null
```

According to sentry in this foreach
https://github.com/matomo-org/matomo/blob/056027d3236491ebb3b60e124ab82786b0cdd72e/plugins/ScheduledReports/API.php#L712-L718
`$parameters` is `null`

This function is called from 
https://github.com/matomo-org/matomo/blob/056027d3236491ebb3b60e124ab82786b0cdd72e/plugins/ScheduledReports/API.php#L348

with the following variables set:

&nbsp; | &nbsp;
--- | ---
date | 2019-03-04
idReport | 4
language | en
outputType | 2
period | week

Of course one could simply add a not null check, but I want to make sure there is no larger underlying error.

**Comment by sgiehl** [comment]
@Findus23  could you check if the report that is sent does have any parameters set in the database?

**Comment by Findus23** [comment]
@sgiehl You are right. It seems like something went wrong a long time ago:
```
+------------+----------+---------+---------------+-------------+----------+--------+--------+----------+-----------+--------------+---------------------+---------------------+-----------+---------------------------------+----------------------------+
|   idreport |   idsite | login   | description   |   idsegment | period   |   hour | type   | format   | reports   | parameters   | ts_created          | ts_last_sent        |   deleted |   evolution_graph_within_period |   evolution_graph_period_n |
|------------+----------+---------+---------------+-------------+----------+--------+--------+----------+-----------+--------------+---------------------+---------------------+-----------+---------------------------------+----------------------------|
|          4 |        2 | Lukas   | alle          |      <null> | week     |      4 | email  | html     | Array     | Array        | 2016-08-11 12:32:08 | 2016-09-26 07:00:50 |         0 |                               0 |                     <null> |
+------------+----------+---------+---------------+-------------+----------+--------+--------+----------+-----------+--------------+---------------------+---------------------+-----------+---------------------------------+----------------------------+
```
