### ISSUE TITLE
error message returned in core:archive: Unexpected state: row evolution API call returned empty DataTable\Map.

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14499]
This error was triggered in core:archive for 2 different users, with the same backtrace, where they mention "getSiteSearchCategories" ie. `Piwik\Plugins\ImageGraph\API->get(1, 'day', '2019-04-22,2019...', 'Actions', 'getSiteSearchCategories', 'evolution', '2', false, false, true, 700, 200, 9, 11, true, false, false, '222222', 'FFFFFF', 'CCCCCC', false, true, false, false)`

Maybe this can be reproduced by creating  a scheduled email report which includes the SiteSearch.getSiteSearchCategories report and an evolution graph?

See below the error message and backtrace. I could provide the dump on request but maybe it's not necesary to fix the issue, somehow?

```
 Uncaught exception in API: /var/www/html/plugins/API/RowEvolution.php(362): Unexpected state: row evolution API call returned empty DataTable\Map.
Unexpected state: row evolution API call returned empty DataTable\Map.
#0 /var/www/html/plugins/API/RowEvolution.php(505): Piwik\Plugins\API\RowEvolution->enhanceRowEvolutionMetaData(Array, Object(Piwik\DataTable\Map))
#1 /var/www/html/plugins/API/RowEvolution.php(71): Piwik\Plugins\API\RowEvolution->getMultiRowEvolution(Object(Piwik\DataTable\Map), Array, 'Actions', 'getSiteSearchCa...', Array, 'nb_visits', '1', true)
#2 /var/www/html/plugins/API/API.php(495): Piwik\Plugins\API\RowEvolution->getRowEvolution(1, 'day', '2019-04-22,2019...', 'Actions', 'getSiteSearchCa...', '', false, 'nb_visits', 'ru', Array, '1', true)
#3 [internal function]: Piwik\Plugins\API\API->getRowEvolution(1, 'day', '2019-04-22,2019...', 'Actions', 'getSiteSearchCa...', false, false, 'nb_visits', 'ru', false, '1', true, false)
#4 /var/www/html/core/API/Proxy.php(237): call_user_func_array(Array, Array)
#5 /var/www/html/core/Context.php(28): Piwik\API\Proxy->Piwik\API\{closure}()
#6 /var/www/html/core/API/Proxy.php(328): Piwik\Context::executeWithQueryParameters(Array, Object(Closure))
#7 /var/www/html/core/API/Request.php(265): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'getRowEvolution', Array)
#8 /var/www/html/core/API/Request.php(507): Piwik\API\Request->process()
#9 /var/www/html/plugins/ImageGraph/API.php(318): Piwik\API\Request::processRequest('API.getRowEvolu...', Array)
#10 [internal function]: Piwik\Plugins\ImageGraph\API->get(1, 'day', '2019-04-22,2019...', 'Actions', 'getSiteSearchCa...', 'evolution', '2', false, false, true, 700, 200, 9, 11, true, false, false, '222222', 'FFFFFF', 'CCCCCC', false, true, false, false)
#11 /var/www/html/core/API/Proxy.php(237): call_user_func_array(Array, Array)
#12 /var/www/html/core/Context.php(28): Piwik\API\Proxy->Piwik\API\{closure}()
#13 /var/www/html/core/API/Proxy.php(328): Piwik\Context::executeWithQueryParameters(Array, Object(Closure))
#14 /var/www/html/core/API/Request.php(265): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'get', Array)
#15 /var/www/html/core/ReportRenderer.php(268): Piwik\API\Request->process()
#16 /var/www/html/core/ReportRenderer/Html.php(175): Piwik\ReportRenderer::getStaticGraph(Array, 700, 200, true, NULL)
#17 /var/www/html/core/ReportRenderer/Html.php(139): Piwik\ReportRenderer\Html->getAttachment(Array, Array, '\xD0\x92\xD1\x82\xD0\xBE\xD1\x80\xD0\xBD\xD0\xB8\xD0\xBA,...')
#18 /var/www/html/plugins/ScheduledReports/API.php(1012): Piwik\ReportRenderer\Html->getAttachments(Array, Array, '\xD0\x92\xD1\x82\xD0\xBE\xD1\x80\xD0\xBD\xD0\xB8\xD0\xBA,...')
#19 /var/www/html/plugins/ScheduledReports/API.php(538): Piwik\Plugins\ScheduledReports\API->getAttachments(Object(Piwik\ReportRenderer\Html), Array, Array, '\xD0\x92\xD1\x82\xD0\xBE\xD1\x80\xD0\xBD\xD0\xB8\xD0\xBA,...')
#20 /var/www/html/plugins/ScheduledReports/API.php(599): Piwik\Plugins\ScheduledReports\API->generateReport('2', '2019-05-21', 'ru', 2, 'day')
#21 /var/www/html/core/Context.php(75): Piwik\Plugins\ScheduledReports\API->Piwik\Plugins\ScheduledReports\{closure}()
#22 /var/www/html/plugins/ScheduledReports/API.php(670): Piwik\Context::changeIdSite('1', Object(Closure))
#23 [internal function]: Piwik\Plugins\ScheduledReports\API->sendReport('2')
#24 /var/www/html/core/Scheduler/Scheduler.php(264): call_user_func(Array, '2')
#25 /var/www/html/core/Scheduler/Scheduler.php(136): Piwik\Scheduler\Scheduler->executeTask(Object(Piwik\Scheduler\Task))
#26 /var/www/html/plugins/CoreAdminHome/API.php(66): Piwik\Scheduler\Scheduler->run()
#27 /var/www/html/core/CronArchive.php(612): Piwik\Plugins\CoreAdminHome\API->runScheduledTasks()
#28 /var/www/html/core/CronArchive.php(317): Piwik\CronArchive->runScheduledTasks()
#29 /var/www/html/core/Access.php(628): Piwik\CronArchive->Piwik\{closure}()
#30 /var/www/html/core/CronArchive.php(319): Piwik\Access::doAsSuperUser(Object(Closure))
#31 /var/www/html/plugins/CoreConsole/Commands/CoreArchiver.php(27): Piwik\CronArchive->main()
#32 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\CoreConsole\Commands\CoreArchiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/html/core/Console.php(98): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/html/core/Access.php(628): Piwik\Console->Piwik\{closure}()
#38 /var/www/html/core/Console.php(99): Piwik\Access::doAsSuperUser(Object(Closure))
#39 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/html/console(27): Symfony\Component\Console\Application->run()
#41 {main} 
```

**Comment by katebutler** [comment]
This exception is the "normal" behaviour when there is no data in the datatable. It seems silly that we would get so deep into the code before we notice this, so I'm adding a check much earlier in the process to fail gracefully when there is no data.
