### ISSUE TITLE
Transitions: Issues displaying with Transition of Action URLs under a Custom Dimension

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#15256]
Issue: When viewing a transition report for an Action URL under a Custom Dimension displaying an error "Either action had no pageviews during the period or it is invalid"
![transition_error](https://user-images.githubusercontent.com/26726594/70493723-8e3d7900-1b6d-11ea-93b0-4a6672e0b67d.PNG)

**Step to reproduce:**
1. Create a Custom Dimension
2. View the Custom Dimension report under "Behaviour"
3. Click on transitions icon in the 'Action URL"
![transition_error1](https://user-images.githubusercontent.com/26726594/70493984-7d413780-1b6e-11ea-934f-3375c9759500.PNG)

Also see: https://github.com/matomo-org/matomo/issues/3899

_Note: getting error only when viewing transitions for outlinks and download links_

**Comment by pranab155** [comment]
Adding Error log for same 
Error occurred in MATOMO log:
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] Uncaught exception in API: <MATOMO installation directory>/matomo/plugins/Transitions/API.php(177): NoDataForAction
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] NoDataForAction
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #0 <MATOMO installation directory>/matomo/plugins/Transitions/API.php(86): Piwik\Plugins\Transitions\API->addInternalReferrers(Object(Piwik\DataAccess\LogAggregator), Array, '1443390', 'url', false)
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #1 [internal function]: Piwik\Plugins\Transitions\API->getTransitionsForAction('go.com...', 'url', '19', Object(Piwik\Period\Day), 'yesterday', Object(Piwik\Segment), false, 'all')
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #2 <MATOMO installation directory>/matomo/core/API/Proxy.php(237): call_user_func_array(Array, Array)
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #3 <MATOMO installation directory>/matomo/core/Context.php(28): Piwik\API\Proxy->Piwik\API\{closure}()
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #4 <MATOMO installation directory>/matomo/core/API/Proxy.php(328): Piwik\Context::executeWithQueryParameters(Array, Object(Closure))
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #5 <MATOMO installation directory>/matomo/core/API/Request.php(265): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'getTransitionsF...', Array)
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #6 <MATOMO installation directory>/matomo/plugins/API/Controller.php(41): Piwik\API\Request->process()
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #7 [internal function]: Piwik\Plugins\API\Controller->index()
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #8 <MATOMO installation directory>/matomo/core/FrontController.php(589): call_user_func_array(Array, Array)
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #9 <MATOMO installation directory>/matomo/core/FrontController.php(165): Piwik\FrontController->doDispatch('API', false, Array)
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #10 <MATOMO installation directory>/matomo/core/dispatch.php(34): Piwik\FrontController->dispatch()
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #11 <MATOMO installation directory>/matomo/index.php(29): require_once('/apache/httpd-2...')
ERROR API[2019-11-26 11:49:22 UTC] [3ecaa] #12 {main}
