### ISSUE TITLE
Geoip2 update: Suggested server cannot be resolved

### ISSUE THREAD

**Issue by mklemme1** [matomo-org/matomo#15339]
I use the built-in updater to get the maxmind city DB. 
The server name geolite.maxmind.com cannot be resolved any more. 
Is there an alternative?

Thanks
  Michael 

```
ERROR [2020-01-01 09:13:16] 31416  /var/www/vhosts/xxxx/piwik/plugins/GeoIp2/GeoIP2AutoUpdater.php(140): GeoIP2AutoUpdater: failed to download 'https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz' to '/var/www/vhosts/xxxx/piwik/tmp/latest/GeoIP2-City.mmdb.tar.gz': curl_exec: Could not resolve host: geolite.maxmind.com. Hostname requested was: geolite.maxmind.com
GeoIP2AutoUpdater: failed to download 'https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz' to '/var/www/vhosts/xxxx/piwik/tmp/latest/GeoIP2-City.mmdb.tar.gz': curl_exec: Could not resolve host: geolite.maxmind.com. Hostname requested was: geolite.maxmind.com
#0 /var/www/vhosts/xxxx/piwik/plugins/GeoIp2/GeoIP2AutoUpdater.php(94): Piwik\Plugins\GeoIp2\GeoIP2AutoUpdater->downloadFile('loc', 'https://geolite...')
#1 [internal function]: Piwik\Plugins\GeoIp2\GeoIP2AutoUpdater->update(NULL)
#2 /var/www/vhosts/xxxx/piwik/core/Scheduler/Scheduler.php(264): call_user_func(Array, NULL)
#3 /var/www/vhosts/xxxx/piwik/core/Scheduler/Scheduler.php(136): Piwik\Scheduler\Scheduler->executeTask(Object(Piwik\Plugins\GeoIp2\GeoIP2AutoUpdater))
#4 /var/www/vhosts/xxxx/piwik/plugins/CoreAdminHome/API.php(65): Piwik\Scheduler\Scheduler->run()
#5 /var/www/vhosts/xxxx/piwik/core/CronArchive.php(629): Piwik\Plugins\CoreAdminHome\API->runScheduledTasks()
#6 /var/www/vhosts/xxxx/piwik/core/CronArchive.php(325): Piwik\CronArchive->runScheduledTasks()
#7 /var/www/vhosts/xxxx/piwik/core/Access.php(639): Piwik\CronArchive->Piwik\{closure}()
#8 /var/www/vhosts/xxxx/piwik/core/CronArchive.php(327): Piwik\Access::doAsSuperUser(Object(Closure))
#9 /var/www/vhosts/xxxx/piwik/plugins/CoreConsole/Commands/CoreArchiver.php(27): Piwik\CronArchive->main()
#10 /var/www/vhosts/xxxx/piwik/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/vhosts/xxxx/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/vhosts/xxxx/piwik/vendor/symfony/console/Symfony/Component/Console/
```

**Comment by daerentis** [comment]
We now need an account at Maxmind to download the GeLite2 Database.

https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by sgiehl** [comment]
see #15308 and #15319

**Comment by mpdude** [comment]
Is there anything we can do to disable these update attempts and avoid the error message until the issues (mostly #15308) have been resolved?

**Comment by daerentis** [comment]
Try to remove the URL to the Maxmind DB in the Matomo settings

**Comment by sgiehl** [comment]
You can create an account at maxmind and use the account specific download-URL for updating, or set the url to the one from db-ip: https://download.db-ip.com/free/dbip-city-lite-2020-01.mmdb.gz
