### ISSUE TITLE
Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction - in plugin Funnels

### ISSUE THREAD

**Issue by xbenjii** [matomo-org/matomo#15635]
Hi,
Just had the following error when archiving.
PHP: 7.3.13
Matomo: 3.13.3
Funnels: 3.1.20
MySQL (RDS Aurora): 5.6.10

```
SUMMARY OF ERRORS
INFO [2020-02-28 09:07:05] 9361  Error: Got invalid response from API request: ?module=API&method=API.get&idSite=3&period=week&date=last1&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:25502:"SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction - in plugin Funnels 
#0 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(133): Piwik\ArchiveProcessor\PluginsArchiver->callAggregateAllPlugins('2677', '273', false) 
#1 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(79): Piwik\ArchiveProcessor\Loader->prepareAllPluginsArchive('2677', '273') 
#2 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(60): Piwik\ArchiveProcessor\Loader->prepareArchiveImpl('VisitsSummary') 
#3 /HD1/vhosts/insights.mydomain.co.uk/core/Context.php(75): Piwik\ArchiveProcessor\Loader->Piwik\ArchiveProcessor\{closure}() 
#4 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(61): Piwik\Context::changeIdSite(3, Object(Closure)) 
#5 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(871): Piwik\ArchiveProcessor\Loader->prepareArchive('VisitsSummary') 
#6 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(678): Piwik\Archive->prepareArchive(Array, Object(Piwik\Site), Object(Piwik\Period\Day)) 
#7 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(620): Piwik\Archive->cacheArchiveIdsAfterLaunching(Array, Array) 
#8 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(549): Piwik\Archive->getArchiveIds(Array) 
#9 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(303): Piwik\Archive->get(Array, 'numeric') 
#10 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor.php(571): Piwik\Archive->getDataTableFromNumeric(Array) 
#11 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor.php(258): Piwik\ArchiveProcessor->getAggregatedNumericMetrics(Array, false) 
#12 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/PluginsArchiver.php(307): Piwik\ArchiveProcessor->aggregateNumericMetrics(Array) 
#13 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/PluginsArchiver.php(108): Piwik\ArchiveProcessor\PluginsArchiver->aggregateMultipleVisitsMetrics() 
#14 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(127): Piwik\ArchiveProcessor\PluginsArchiver->callAggregateCoreMetrics() 
#15 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(79): Piwik\ArchiveProcessor\Loader->prepareAllPluginsArchive(false, false) 
#16 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(60): Piwik\ArchiveProcessor\Loader->prepareArchiveImpl('VisitsSummary') 
#17 /HD1/vhosts/insights.mydomain.co.uk/core/Context.php(75): Piwik\ArchiveProcessor\Loader->Piwik\ArchiveProcessor\{closure}() 
#18 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(61): Piwik\Context::changeIdSite(3, Object(Closure)) 
#19 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(871): Piwik\ArchiveProcessor\Loader->prepareArchive('VisitsSummary') 
#20 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(678): Piwik\Archive->prepareArchive(Array, Object(Piwik\Site), Object(Piwik\Period\Week)) 
#21 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(620): Piwik\Archive->cacheArchiveIdsAfterLaunching(Array, Array) 
#22 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(549): Piwik\Archive->getArchiveIds(Array) 
#23 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(303): Piwik\Archive->get(Array, 'numeric') 
#24 /HD1/vhosts/insights.mydomain.co.uk/plugins/VisitsSummary/API.php(36): Piwik\Archive->getDataTableFromNumeric(Array) 
#25 [internal function]: Piwik\Plugins\VisitsSummary\API->get('3', 'week', 'last1', false, Array) 
#26 /HD1/vhosts/insights.mydomain.co.uk/core/API/Proxy.php(237): call_user_func_array(Array, Array) 
#27 /HD1/vhosts/insights.mydomain.co.uk/core/Context.php(28): Piwik\API\Proxy->Piwik\API\{closure}() 
#28 /HD1/vhosts/insights.mydomain.co.uk/core/API/Proxy.php(328): Piwik\Context::executeWithQueryParameters(Array, Object(Closure)) 
#29 /HD1/vhosts/insights.mydomain.co.uk/plugins/API/API.php(435): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'get', Array) 
#30 [internal function]: Piwik\Plugins\API\API->get('3', 'week', 'last1', false, Array) 
#31 /HD1/vhosts/insights.mydomain.co.uk/core/API/Proxy.php(237): call_user_func_array(Array, Array) 
#32 /HD1/vhosts/insights.mydomain.co.uk/core/Context.php(28): Piwik\API\Proxy->Piwik\API\{closure}() 
#33 /HD1/vhosts/insights.mydomain.co.uk/core/API/Proxy.php(328): Piwik\Context::executeWithQueryParameters(Array, Object(Closure)) 
#34 /HD1/vhosts/insights.mydomain.co.uk/core/API/Request.php(2
 66): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'get', Array) 
#35 /HD1/vhosts/insights.mydomain.co.uk/plugins/API/Controller.php(41): Piwik\API\Request->process() 
#36 [internal function]: Piwik\Plugins\API\Controller->index() 
#37 /HD1/vhosts/insights.mydomain.co.uk/core/FrontController.php(589): call_user_func_array(Array, Array) 
#38 /HD1/vhosts/insights.mydomain.co.uk/core/FrontController.php(165): Piwik\FrontController->doDispatch('API', false, Array) 
#39 /HD1/vhosts/insights.mydomain.co.uk/core/dispatch.php(34): Piwik\FrontController->dispatch() 
#40 /HD1/vhosts/insights.mydomain.co.uk/index.php(27): require_once('/HD1/vhosts/ins...') 
#41 /HD1/vhosts/insights.mydomain.co.uk/core/CliMulti/RequestCommand.php(79): require_once('/HD1/vhosts/ins...') 
#42 /HD1/vhosts/insights.mydomain.co.uk/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\CliMulti\RequestCommand->execute(Object(Symfony
 \Component\Console\Input\ArgvInput), Object(Symfony\Compo
ERROR [2020-02-28 09:07:05] 9361  1 total errors during this script execution, please investigate and try and fix these errors.
ERROR [2020-02-28 09:07:05] 9361  Uncaught exception: /HD1/vhosts/insights.mydomain.co.uk/core/CronArchive.php(602): 1 total errors during this script execution, please investigate and try and fix these errors.
1 total errors during this script execution, please investigate and try and fix these errors.

#0 /HD1/vhosts/insights.mydomain.co.uk/core/CronArchive.php(595): Piwik\CronArchive->logFatalError('1 total errors ...')

#1 /HD1/vhosts/insights.mydomain.co.uk/core/CronArchive.php(330): Piwik\CronArchive->end()

#2 /HD1/vhosts/insights.mydomain.co.uk/core/Access.php(635): Piwik\CronArchive->Piwik\{closure}()

#3 /HD1/vhosts/insights.mydomain.co.uk/core/CronArchive.php(331): Piwik\Access::doAsSuperUser(Object(Closure))

#4 /HD1/vhosts/insights.mydomain.co.uk/plugins/CoreConsole/Commands/CoreArchiver.php(27): Piwik\CronArchive->main()

#5 /HD1/vhosts/insights.mydomain.co.uk/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#6 /HD1/vhosts/insights.mydomain.co.uk/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#7 /HD1/vhosts/insights.mydomain.co.uk/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\CoreConsole\Commands\CoreArchiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#8 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#9 /HD1/vhosts/insights.mydomain.co.uk/core/Console.php(140): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#10 /HD1/vhosts/insights.mydomain.co.uk/core/Access.php(644): Piwik\Console->Piwik\{closure}()

#11 /HD1/vhosts/insights.mydomain.co.uk/core/Console.php(141): Piwik\Access::doAsSuperUser(Object(Closure))

#12 /HD1/vhosts/insights.mydomain.co.uk/core/Console.php(93): Piwik\Console->doRunImpl(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#13 /HD1/vhosts/insights.mydomain.co.uk/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#14 /HD1/vhosts/insights.mydomain.co.uk/console(32): Symfony\Component\Console\Application->run()

#15 {main}
```

**Comment by xbenjii** [comment]
Another one with a slightly different stacktrace
```
SUMMARY OF ERRORS
INFO [2020-02-28 11:07:55] 7895  Error: Got invalid response from API request: ?module=API&method=API.get&idSite=3&period=year&date=last2&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:31457:"SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction - in plugin Funnels 
#0 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(133): Piwik\ArchiveProcessor\PluginsArchiver->callAggregateAllPlugins('5506', '567', false) 
#1 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(79): Piwik\ArchiveProcessor\Loader->prepareAllPluginsArchive('5506', '567') 
#2 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(60): Piwik\ArchiveProcessor\Loader->prepareArchiveImpl('VisitsSummary') 
#3 /HD1/vhosts/insights.mydomain.co.uk/core/Context.php(75): Piwik\ArchiveProcessor\Loader->Piwik\ArchiveProcessor\{closure}() 
#4 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(61): Piwik\Context::changeIdSite(3, Object(Closure)) 
#5 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(871): Piwik\ArchiveProcessor\Loader->prepareArchive('VisitsSummary') 
#6 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(678): Piwik\Archive->prepareArchive(Array, Object(Piwik\Site), Object(Piwik\Period\Day)) 
#7 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(620): Piwik\Archive->cacheArchiveIdsAfterLaunching(Array, Array) 
#8 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(549): Piwik\Archive->getArchiveIds(Array) 
#9 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(303): Piwik\Archive->get(Array, 'numeric') 
#10 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor.php(571): Piwik\Archive->getDataTableFromNumeric(Array) 
#11 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor.php(258): Piwik\ArchiveProcessor->getAggregatedNumericMetrics(Array, false) 
#12 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/PluginsArchiver.php(307): Piwik\ArchiveProcessor->aggregateNumericMetrics(Array) 
#13 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/PluginsArchiver.php(108): Piwik\ArchiveProcessor\PluginsArchiver->aggregateMultipleVisitsMetrics() 
#14 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(127): Piwik\ArchiveProcessor\PluginsArchiver->callAggregateCoreMetrics() 
#15 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(79): Piwik\ArchiveProcessor\Loader->prepareAllPluginsArchive(false, false) 
#16 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(60): Piwik\ArchiveProcessor\Loader->prepareArchiveImpl('VisitsSummary') 
#17 /HD1/vhosts/insights.mydomain.co.uk/core/Context.php(75): Piwik\ArchiveProcessor\Loader->Piwik\ArchiveProcessor\{closure}() 
#18 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(61): Piwik\Context::changeIdSite(3, Object(Closure)) 
#19 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(871): Piwik\ArchiveProcessor\Loader->prepareArchive('VisitsSummary') 
#20 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(678): Piwik\Archive->prepareArchive(Array, Object(Piwik\Site), Object(Piwik\Period\Month)) 
#21 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(620): Piwik\Archive->cacheArchiveIdsAfterLaunching(Array, Array) 
#22 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(549): Piwik\Archive->getArchiveIds(Array) 
#23 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(303): Piwik\Archive->get(Array, 'numeric') 
#24 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor.php(571): Piwik\Archive->getDataTableFromNumeric(Array) 
#25 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor.php(258): Piwik\ArchiveProcessor->getAggregatedNumericMetrics(Array, false) 
#26 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/PluginsArchiver.php(307): Piwik\ArchiveProcessor->aggregateNumericMetrics(Array) 
#27 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/PluginsArchiver.php(108): Piwik\ArchiveProcessor\PluginsArchiver->aggregateMultipleVisitsMetrics() 
#28 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(127): Piwik\ArchiveProcessor\PluginsArchiver->callAggregateCoreMetrics() 
#29 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(79): Piwik\ArchiveProcessor\Loader->prepareAllPluginsArchive(false, false) 
#30 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(60): Piwik\ArchiveProcessor\Loader->prepareArchiveImpl('VisitsSummary') 
#31 /HD1/vhosts/insights.mydomain.co.uk/core/Context.php(75): Piwik\ArchiveProcessor\Loader->Piwik\ArchiveProcessor\{closure}() 
#32 /HD1/vhosts/insights.mydomain.co.uk/core/ArchiveProcessor/Loader.php(61): Piwik\Context::changeIdSite(3, Object(Closure)) 
#33 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(871): Piwik\ArchiveProcessor\Loader->prepareArchive('VisitsSummary') 
#34 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(678): Piwik\Archive->prepareArchive(Array, Object(Piwik\Site), Object(Piwik\Period\Year)) 
#35 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(620): Piwik\Archive->cacheArchiveIdsAfterLaunching(Array, Array) 
#36 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(549): Piwik\Archive->getArchiveIds(Array) 
#37 /HD1/vhosts/insights.mydomain.co.uk/core/Archive.php(303): Piwik\Archive->get(Array, 'numeric') 
#38 /HD1/vhosts/insights.mydomain.co.uk/plugins/VisitsSummary/API.php(36): Piwik\Archive->getDataTableFromNumeric(Array) 
#39 [internal function]: Piwik\Plugins\VisitsSummary\API->get('3', 'year', 'last2', false, Array) 
#40 /HD1/vhosts/insights.mydomain.co.uk/core/API/Proxy.php(237): call_u
ERROR [2020-02-28 11:07:55] 7895  1 total errors during this script execution, please investigate and try and fix these errors.
ERROR [2020-02-28 11:07:55] 7895  Uncaught exception: /HD1/vhosts/insights.mydomain.co.uk/core/CronArchive.php(602): 1 total errors during this script execution, please investigate and try and fix these errors.
1 total errors during this script execution, please investigate and try and fix these errors.

#0 /HD1/vhosts/insights.mydomain.co.uk/core/CronArchive.php(595): Piwik\CronArchive->logFatalError('1 total errors ...')

#1 /HD1/vhosts/insights.mydomain.co.uk/core/CronArchive.php(330): Piwik\CronArchive->end()

#2 /HD1/vhosts/insights.mydomain.co.uk/core/Access.php(635): Piwik\CronArchive->Piwik\{closure}()

#3 /HD1/vhosts/insights.mydomain.co.uk/core/CronArchive.php(331): Piwik\Access::doAsSuperUser(Object(Closure))

#4 /HD1/vhosts/insights.mydomain.co.uk/plugins/CoreConsole/Commands/CoreArchiver.php(27): Piwik\CronArchive->main()

#5 /HD1/vhosts/insights.mydomain.co.uk/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#6 /HD1/vhosts/insights.mydomain.co.uk/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#7 /HD1/vhosts/insights.mydomain.co.uk/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\CoreConsole\Commands\CoreArchiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#8 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#9 /HD1/vhosts/insights.mydomain.co.uk/core/Console.php(140): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#10 /HD1/vhosts/insights.mydomain.co.uk/core/Access.php(644): Piwik\Console->Piwik\{closure}()

#11 /HD1/vhosts/insights.mydomain.co.uk/core/Console.php(141): Piwik\Access::doAsSuperUser(Object(Closure))

#12 /HD1/vhosts/insights.mydomain.co.uk/core/Console.php(93): Piwik\Console->doRunImpl(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#13 /HD1/vhosts/insights.mydomain.co.uk/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#14 /HD1/vhosts/insights.mydomain.co.uk/console(32): Symfony\Component\Console\Application->run()

#15 {main}
```

**Comment by tsteur** [comment]
@xbenjii could you email our support about this one as it might be related to a premium feature? That be great. Email is shop at innocraft.com

Thanks
