### ISSUE TITLE
GeoIP2AutoUpdater: failed to unzip for db-ip.com

### ISSUE THREAD

**Issue by c-prompt** [matomo-org/matomo#15763]
Just received a few cron errors:

```
ERROR [2020-04-01 00:09:52] 29613  /home/mysite/public_html/matomo/plugins/GeoIp2/GeoIP2AutoUpdater.php(172): GeoIP2AutoUpdater: failed to unzip '/home/mysite/public_html/matomo/tmp/latest/DBIP-City.mmdb.gz' after downloading 'https://download.db-ip.com/free/dbip-city-lite-2020-04.mmdb.gz': The downloaded file is not a valid geolocation database. Please re-check the URL or download the file manually.
GeoIP2AutoUpdater: failed to unzip '/home/mysite/public_html/matomo/tmp/latest/DBIP-City.mmdb.gz' after downloading 'https://download.db-ip.com/free/dbip-city-lite-2020-04.mmdb.gz': The downloaded file is not a valid geolocation database. Please re-check the URL or download the file manually.
#0 /home/mysite/public_html/matomo/plugins/GeoIp2/GeoIP2AutoUpdater.php(99): Piwik\Plugins\GeoIp2\GeoIP2AutoUpdater->downloadFile()
#1 [internal function]: Piwik\Plugins\GeoIp2\GeoIP2AutoUpdater->update()
#2 /home/mysite/public_html/matomo/core/Scheduler/Scheduler.php(264): call_user_func()
#3 /home/mysite/public_html/matomo/core/Scheduler/Scheduler.php(136): Piwik\Scheduler\Scheduler->executeTask()
#4 /home/mysite/public_html/matomo/plugins/CoreAdminHome/API.php(65): Piwik\Scheduler\Scheduler->run()
#5 /home/mysite/public_html/matomo/core/CronArchive.php(642): Piwik\Plugins\CoreAdminHome\API->runScheduledTasks()
#6 /home/mysite/public_html/matomo/core/CronArchive.php(329): Piwik\CronArchive->runScheduledTasks()
#7 /home/mysite/public_html/matomo/core/Access.php(635): Piwik\CronArchive->Piwik\{closure}()
#8 /home/mysite/public_html/matomo/core/CronArchive.php(331): Piwik\Access::doAsSuperUser()
#9 /home/mysite/public_html/matomo/plugins/CoreConsole/Commands/CoreArchiver.php(27): Piwik\CronArchive->main() #10 /home/mysite/public_html/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute()
#11 /home/mysite/public_html/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run()
#12 /home/mysite/public_html/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand()
#13 [internal function]: Symfony\Component\Console\Application->doRun()
#14 /home/mysite/public_html/matomo/core/Console.php(140): call_user_func()
#15 /home/mysite/public_html/matomo/core/Access.php(644): Piwik\Console->Piwik\{closure}()
#16 /home/mysite/public_html/matomo/core/Console.php(141): Piwik\Access::doAsSuperUser()
#17 /home/mysite/public_html/matomo/core/Console.php(93): Piwik\Console->doRunImpl()
#18 /home/mysite/public_html/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun()
#19 /home/mysite/public_html/matomo/console(32): Symfony\Component\Console\Application->run()
#20 {main}
```

**Comment by tsteur** [comment]
Does Matomo have file permission there?

**Comment by c-prompt** [comment]
Matomo does have write permission. Nothing had changed and the cron erred twice so I thought it might be a problem with the zip file. However, it seems like it finally unzipped so not sure what the problem was. Closing.

**Comment by Findus23** [comment]
I think this is most likely the same case as https://forum.matomo.org/t/geoip2autoupdater-php/36707

April started, Matomo tried to download the dbip-city-lite-2020-04.mmdb.gz, but it was not yet online.
