### ISSUE TITLE
TagManager error in 3.13.5

### ISSUE THREAD

**Issue by jorgeuos** [matomo-org/matomo#15884]
After updating Matomo Core to 3.13.5 I get this error when trying to re-generate JS scripts.

```
bash-5.0$ ./console tagmanager:regenerate-released-containers
ERROR [2020-04-29 18:08:37] 73  There was an error while regenerating container releases: No entry or class found for 'Piwik\Plugins\CustomJsTracker\TrackerUpdater'#0 /var/www/html/core/Container/StaticContainer.php(80): DI\Container->get('Piwik\\Plugins\\C...')
#1 /var/www/html/plugins/TagManager/Template/Tag/MatomoTag.php(151): Piwik\Container\StaticContainer::get('Piwik\\Plugins\\C...')
#2 /var/www/html/plugins/TagManager/Context/BaseContext/TemplateLocator.php(54): Piwik\Plugins\TagManager\Template\Tag\MatomoTag->loadTemplate('web', Array)
#3 /var/www/html/plugins/TagManager/Context/WebContext.php(110): Piwik\Plugins\TagManager\Context\BaseContext\TemplateLocator->loadTagTemplate(Array, 'web')
#4 /var/www/html/plugins/TagManager/Model/Container.php(123): Piwik\Plugins\TagManager\Context\WebContext->generate(Array)
#5 /var/www/html/plugins/TagManager/TagManager.php(255): Piwik\Plugins\TagManager\Model\Container->generateContainer(3, '1dOA9X95')
#6 /var/www/html/core/Context.php(75): Piwik\Plugins\TagManager\TagManager->Piwik\Plugins\TagManager\{closure}()
#7 /var/www/html/plugins/TagManager/TagManager.php(256): Piwik\Context::changeIdSite(3, Object(Closure))
#8 /var/www/html/core/Access.php(635): Piwik\Plugins\TagManager\TagManager->Piwik\Plugins\TagManager\{closure}()
#9 /var/www/html/plugins/TagManager/TagManager.php(264): Piwik\Access::doAsSuperUser(Object(Closure))
#10 [internal function]: Piwik\Plugins\TagManager\TagManager->regenerateReleasedContainers()
#11 /var/www/html/core/EventDispatcher.php(141): call_user_func_array(Array, Array)
#12 /var/www/html/core/Piwik.php(775): Piwik\EventDispatcher->postEvent('TagManager.rege...', Array, false, Array)
#13 /var/www/html/plugins/TagManager/Commands/RegenerateContainers.php(26): Piwik\Piwik::postEvent('TagManager.rege...')
#14 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\TagManager\Commands\RegenerateContainers->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\TagManager\Commands\RegenerateContainers), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/core/Console.php(140): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/core/Access.php(644): Piwik\Console->Piwik\{closure}()
#20 /var/www/html/core/Console.php(141): Piwik\Access::doAsSuperUser(Object(Closure))
#21 /var/www/html/core/Console.php(93): Piwik\Console->doRunImpl(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/console(32): Symfony\Component\Console\Application->run()
#24 {main}
Done
Error: error or warning logs detected, exit 1
bash-5.0$ php -v
PHP 7.3.17 (cli) (built: Apr 24 2020 18:17:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.17, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.17, Copyright (c) 1999-2018, by Zend Technologies
bash-5.0$
```
Running PHP 7.3.17
I will try to debug this locally.

**Comment by tsteur** [comment]
@jorgeuos is there any chance you are updating the Tag Manager through Git or similar?

> No entry or class found for 'Piwik\Plugins\CustomJsTracker\TrackerUpdater'#

This indicates that potentially the Matomo 4 version of the Tag Manager is used (which is not compatible with Matomo 3). Not sure how this would happen though.

**Comment by jorgeuos** [comment]
Ah, Thats a good lead actually. I need to go through how we fetch the plugins. Thanks.

**Comment by jorgeuos** [comment]
Got it working now thanks!

**Comment by tsteur** [comment]
Awesome @jorgeuos do you mind letting us know what it was?

**Comment by jorgeuos** [comment]
We pre-build our docker images, and TagManager was tagged with wrong release. So it was our workflow.
