### ISSUE TITLE
New installation Parameter Resolver OverjectCreator

### ISSUE THREAD

**Issue by mertz3hack** [matomo-org/matomo#16005]
Hello all
I went to do a new installation on a shared server and got this error.  I was looking to see if there is some dependency missing but haven't found it.

Thoughts?

```
Fatal error: Uncaught Error: Class 'DI\Definition\Resolver\ParameterResolver' not found in /home/site/public_html/site/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php:51 Stack trace: #0 /home/site/public_html/matomo/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(95): DI\Definition\Resolver\ObjectCreator->__construct(Object(DI\Definition\Resolver\ResolverDispatcher), Object(DI\Proxy\ProxyFactory)) #1 /home/site/public_html/matomo/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(56): DI\Definition\Resolver\ResolverDispatcher->getDefinitionResolver(Object(DI\Definition\ObjectDefinition)) #2 /home/site/public_html/matomo/vendor/php-di/php-di/src/DI/Container.php(303): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array) #3 /home/site/public_html/matomo/vendor/php-di/php-di/src/DI/Container.php(131): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition)) #4 /home/site/public_ht in /home/site/public_html/matomo/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php on line 51

Fatal error: Uncaught DI\DependencyException: Circular dependency detected while trying to resolve entry 'Psr\Log\LoggerInterface' in /home/site/public_html/matomo/vendor/php-di/php-di/src/DI/Container.php:297 Stack trace: #0 /home/site/public_html/matomo/vendor/php-di/php-di/src/DI/Container.php(131): DI\Container->resolveDefinition(Object(DI\Definition\AliasDefinition)) #1 /home/site/public_html/matomo/core/Container/StaticContainer.php(80): DI\Container->get('Psr\\Log\\LoggerI...') #2 /home/site/public_html/matomo/core/FrontController.php(265): Piwik\Container\StaticContainer::get('Psr\\Log\\LoggerI...') #3 [internal function]: Piwik\FrontController::triggerSafeModeWhenError() #4 {main} thrown in /home/site/public_html/matomo/vendor/php-di/php-di/src/DI/Container.php on line 297
```

**Comment by tsteur** [comment]
@mertz3hack thanks for creating the issue. How did you install Matomo? Did you download the Matomo zip from our website?

**Comment by mertz3hack** [comment]
@tsteur I originally downloaded from Github by cloning.  After reading your comment I went and download the latest version form the website and it worked right away.

**Comment by tsteur** [comment]
Glad it works now @mertz3hack
