### ISSUE TITLE
Error Call to undefined method Piwik\\DataTable\\Simple::getComparisons()

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16342]
On request `index.php?forceView=1&viewDataTable=sparklines&module=Goals&action=get&idGoal=10&allow_multiple=0&only_summary=1&idSite=2&period=day&date=2020-08-17,2020-08-23&segment=&showtitle=1&random=8740`

following error happened because a data table map was returned instead of a regular data table. And in this case the first row is a dataTable and not a row.

> Error: {"message":"Call to undefined method Piwik\\DataTable\\Simple::getComparisons()","file":"\/plugins\/CoreVisualizations\/Visualizations\/Sparklines.php","line":125,"request_id":"12345","backtrace":" on \/plugins\/CoreVisualizations\/Visualizations\/Sparklines.php(125)\n#0 \/plugins\/CoreVisualizations\/Visualizations\/Sparklines.php(94): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Sparklines->fetchConfiguredSparklines()\n#1 \/core\/Plugin\/Report.php(320): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Sparklines->render()\n#2 \/plugins\/CoreHome\/Controller.php(58): Piwik\\Plugin\\Report->render()\n#3 [internal function]: Piwik\\Plugins\\CoreHome\\Controller->renderReportWidget(Object(Piwik\\Plugins\\Goals\\Reports\\Get))\n#4 \/core\/FrontController.php(590): call_user_func_array(Array, Array)\n#5 \/core\/FrontController.php(165): Piwik\\FrontController->doDispatch('Goals', 'get', Array)\n#6 \/core\/dispatch.php(34): Piwik\\FrontController->dispatch()\n#7 \/index.php(27): require_once('\/c...')\n#8 {main}"}

**Comment by diosmosis** [comment]
@tsteur where did this URL come from? It's failing because of period=day&date=date1,date2 (ie, it's a multi-period query). I think the `sparklines` visualization is meant to be just for a single period. The `sparkline` visualization URLs ( the requests for the actual sparkline images) can handle multiple periods though.

**Comment by tsteur** [comment]
@diosmosis it looks like it came from this:

```
/index.php?forceView=1&viewDataTable=sparklines&module=Goals&action=get&idGoal=6&allow_multiple=0&only_summary=1&idSite=2&period=day&date=2020-08-17,2020-08-23&segment=&showtitle=1&random=2961
```

**Comment by diosmosis** [comment]
@tsteur is the sparklines visualization meant to be used with multi periods?

**Comment by tsteur** [comment]
Haven't looked how it works but would have expected that `period=day&date=2020-08-17,2020-08-23` shows 7 data points one for each day?  I'm not so much into it though

**Comment by diosmosis** [comment]
`period=day&date=2020-08-17,2020-08-23` range should work, but I've never seen sparklines work w/ multi period. If you sent 10 periods, would it show sparklines and metrics next to them for each 10 periods for each metric in the widget? Seems like it's meant to be a single period.

**Comment by tsteur** [comment]
@diosmosis not sure what you mean with multi period? The request URL looks normal I just compared it to a regular request. Why it returned a datatable map not sure. Maybe it does think there's somewhere a multi period or some other issue. The URL was generated by the UI though and also looks good. Maybe some issue with a plugin or something, not sure. 

We can look into it after the Matomo 4 release though.

**Comment by diosmosis** [comment]
There are two visualizations, one is `sparklines` w/ an **s**, and the other is `sparkline`. `sparkline` shows the image, `sparklines` shows a sparkline + metric data for a set of metrics. I don't think it's currently supported to support multiple periods since then there would be a sparkline & metric for every period.

**Comment by diosmosis** [comment]
I guess we could make the sparklines visualization work when a multi period is used by summing up the datatable\map, but I don't think it natively supports it and I don't think the period selector UI supports clicking through to such a period.

**Comment by tsteur** [comment]
If the generated URL is not correct and it's using a multi period, then we'd need to maybe check how the UI would generate this URL as it's maybe a mistake. I'm pretty certain this URL wasn't generated by the user since the request came from our UI. 

Not too important right now though.

**Comment by sgiehl** [comment]
That actually happens when you call the goals page with "invalid" parameters. e.g. something like 
`#?idSite=1&period=day&date=2020-11-23,2020-11-26&segment=&category=Goals_Goals&subcategory=General_Overview`

Most of the charts actually throw an error in that case. Might be something we could handle better, like not requesting any reports at all and open the date selector directly if the date and period parameter combination isn't supported

**Comment by tsteur** [comment]
Sounds good @sgiehl . We could also just show a simple message like "specified date/period combination not supported. please choose a valid date range from the date selector". If it's not trivial we can also simply close the issue though as a wontfix

**Comment by tsteur** [comment]
Reopening this issue again as it's still a problem. Removing the milestone as we'll work on it only if it happens more often


> Call to undefined method Piwik\\DataTable\\Simple::getComparisons()","file":"\/plugins\/CoreVisualizations\/Visualizations\/Sparklines.php","line":126,"request_id":"336ca","backtrace":" on \/plugins\/CoreVisualizations\/Visualizations\/Sparklines.php(126)\n#0 \/plugins\/CoreVisualizations\/Visualizations\/Sparklines.php(94): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Sparklines->fetchConfiguredSparklines()\n#1 \/core\/Plugin\/Report.php(320): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Sparklines->render()\n#2 l\/plugins\/CoreHome\/Controller.php(59): Piwik\\Plugin\\Report->render()\n#3 [internal function]:
